stages:
  - build
  - deploy

services:
  - name: docker:dind
    command: ["--experimental"]

.docker-setup:
  image: docker:stable-git
  before_script:
    - mkdir -p ~/.docker/cli-plugins
    - wget https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx
    - chmod a+x ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use --driver docker-container
    - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"
    - echo "${DOCKERHUB_PASSWORD}" | docker login -u "${DOCKERHUB_USERNAME}" --password-stdin docker.io
    - export BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
    - export VCS_REF="$(git describe --tags --always --dirty)"

.build:
  stage: build
  script:
    - docker buildx build --build-arg version=${VERSION} --platform ${PLATFORM} --tag opensuse-ansible --cache-to "type=local,dest=.cache/${PLATFORM}/${VERSION}" --load .
    - docker run --rm -d --name opensuse-ansible opensuse-ansible
    - docker stop opensuse-ansible
  artifacts:
    paths:
      - .cache
    expire_in: 1 hour

# Latest tag
amd64:latest:
  extends:
    - .build
    - .docker-setup
  variables:
    PLATFORM: linux/amd64
    VERSION: latest

# 15.2 tag
amd64:15.2:
  extends:
    - .build
    - .docker-setup
  variables:
    PLATFORM: linux/amd64
    VERSION: "15.2"

# 15.1 tag
amd64:15.1:
  extends:
    - .build
    - .docker-setup
  variables:
    PLATFORM: linux/amd64
    VERSION: "15.1"

.deploy:
  extends:
    - .docker-setup
  stage: deploy
  script:
    - |
      docker buildx build . --push --platform linux/amd64 \
      --cache-from "type=local,src=.cache/linux/amd64/${VERSION}" \
      --label "org.opencontainers.image.created=${BUILD_DATE}" \
      --label "org.opencontainers.image.revision=${VCS_REF}" \
      --tag ${CI_REGISTRY_IMAGE}:${VERSION} \
      --tag ${DOCKERHUB_REPOSITORY}:${VERSION}
    - docker run -v ${PWD}:/workspace -e DOCKERHUB_USERNAME -e DOCKERHUB_PASSWORD -e DOCKERHUB_REPOSITORY -e README_FILEPATH=/workspace/README.md peterevans/dockerhub-description

deploy:latest:
  extends:
    - .deploy
  variables:
    VERSION: latest

deploy:15.2:
  extends:
    - .deploy
  variables:
    VERSION: "15.2"

deploy:15.1:
  extends:
    - .deploy
  variables:
    VERSION: "15.1"
